We are going to use the famous iris data set for our KNN example. 


The dataset consists of four attributes: sepal-width, sepal-length, petal-width and petal-length. 



These are the attributes of specific types of iris plant. 


The task is to predict the class to which these plants belong. There are three classes in the dataset: Iris-setosa, Iris-versicolor and Iris-virginica. 


Further details of the dataset are available here.
https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html

In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import seaborn as sns
import sklearn
sns.set()

## Question

Please import, preprocess the data, train-test split, feature scale it, make predictions, and please evaluate it. 

Please also calculate the error rate for K values of 1 to 40. 

In each iteration the mean error for predicted values of test set is calculated and the result is appended to the error list.

The next step is to plot the error values against K values.

In [12]:
df = pd.read_csv('iris.csv')

In [37]:
df.shape

(150, 5)

In [28]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [38]:
for n in range(1,41):
    knn = KNeighborsClassifier(n_neighbors=n, metric='euclidean')
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print(n)
    print(confusion_matrix(y_test, y_pred))

1
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
2
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
3
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
4
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
5
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
6
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
7
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
8
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
9
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
10
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
11
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
12
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
13
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
14
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
15
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
16
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
17
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
18
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
19
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
20
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
21
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
22
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
23
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
24
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
25
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
26
[[13  

In [32]:
confusion_matrix(y_test, y_pred) # for k = 5

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])